### ISSUE TITLE
logger library should be updated or removed

### ISSUE THREAD

**Issue by cce** [intelsdi-x/snap-plugin-utilities#38]
The logger library writes `"Logging to stderr"` to stdout in its `init()` block here:
https://github.com/intelsdi-x/snap-plugin-utilities/blob/master/logger/logger.go#L51

That causes the Snap daemon to fail to load the plugin because it is expecting JSON output as the first line on stdout here:
https://github.com/librato/snap/blob/master/control/plugin/execution.go#L124-L139

That means plugins that use the github.com/intelsdi-x/snap-plugin-utilities/logger package will fail to work with the Snap daemon. This is important to note on the README — that this package is unmaintained and no longer compatible with Snap.

From error log output:
```
time="2017-10-17T12:59:04-05:00" level=error msg="error loading plugin" _module=plugin-exec received_response="Logging to stderr"
time="2017-10-17T12:59:04-05:00" level=error msg="load plugin error when starting plugin" _block=load-plugin _module=control-plugin-mgr error="invalid character 'L' looking for beginning of value"
time="2017-10-17T12:59:04-05:00" level=error msg="invalid character 'L' looking for beginning of value" _block=start _module=control autodiscoverpath="X" plugin=Y
```

**Comment by IzabellaRaulin** [comment]
@cce, good catch! Could you provide the name of plugin (or plugins) which uses this package and is affected?

**Comment by IzabellaRaulin** [comment]
cc: @WangJialei-A

**Comment by WangJialei-A** [comment]
@IzabellaRaulin Snap plugin output a json string to stdout while launching and snap daemon will parse the content. It is forbidden to print some debug log while plugin launching. Am I right?
cc: @taotod

**Comment by IzabellaRaulin** [comment]
@WangJialei-A - yes, you are right.

**Comment by trevrosen** [comment]
@IzabellaRaulin @cce this plugin is affected https://github.com/grafana/snap-plugin-collector-kubestate

**Comment by cce** [comment]
@IzabellaRaulin I noticed this library was being used by a few plugins: https://github.com/search?q=github.com%2Fintelsdi-x%2Fsnap-plugin-utilities%2Flogger&type=Code&utf8=%E2%9C%93

https://github.com/intelsdi-x/snap-plugin-collector-active-directory
https://github.com/intelsdi-x/snap-plugin-collector-perfmon
https://github.com/grafana/snap-plugin-collector-kubestate
https://github.com/raintank/snap-plugin-collector-snapstats
